# Generated by Django 3.0.6 on 2020-06-01 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoalbum', '0003_auto_20200601_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='voting_user',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoalbum.Photo')),
                ('voting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
