# Generated by Django 3.0.6 on 2020-06-02 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoalbum', '0005_auto_20200602_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='voting_photo',
        ),
        migrations.AddField(
            model_name='vote',
            name='voting_photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photoalbum.Photo'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voting_user',
        ),
        migrations.AddField(
            model_name='vote',
            name='voting_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
