# Generated by Django 3.0.6 on 2020-06-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0006_auto_20200602_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='votes',
        ),
        migrations.AddField(
            model_name='photo',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
